### PR TITLE
feat: getRoundId

### LINKED ISSUE #182: a method for getting latest round id from a given price feed in synthetic-chain
## Problem Definition
In https://github.com/Agoric/agoric-sdk/pull/10229#discussion_r1790708899 @Chris-Hibbert thought this might be a good idea to add to synthetic-chain. 

## Solution
Implement a method called `getRoundId` with a parameter like `ATOM, stATOM` etc.

### PR DESCRIPTION
**Pull request by turadg**
Closes #182

Trying to land @anilhelvaci 's https://github.com/Agoric/agoric-3-proposals/pull/183 by making it a local PR.

## @agoric/synthetic-chain library

- [X] indicate in the PR description when you expect these to be published and by whom (it's currently a manual process)

Turadg can publish this after it's passing CI.

### CODE REVIEW

**Comment by anilhelvaci** [comment]
Thanks for this @turadg 🙏

**Review by Chris-Hibbert — APPROVED** [review]
I don't understand what @turadg did.  What's a "local PR"?

**Comment by turadg** [comment]
> What's a "local PR"?

One whose branch is in this repo. The other PR is for a branch from a fork.

**Comment by turadg** [comment]
I'm merging this but I won't cut a release just yet. I think there are some more helpers to land before going through the ceremony.

**Pull request merged**
