### PR TITLE
chore: add a method for getting latest round if for a given price feed

### PR DESCRIPTION
**Pull request by anilhelvaci**
closes: https://github.com/Agoric/agoric-3-proposals/issues/182

## Testing considerations
Since most of the code in synthetic-chain do not have tests, I did not want to add bespoke tests for one method. However, I have done `npm pack` moved the tarball file to `z:acceptance` and confirmed all the tests over there still work plus `getRoundId` works as well.

### CODE REVIEW

**Comment by anilhelvaci** [comment]
cc @Chris-Hibbert

**Review by Chris-Hibbert — APPROVED** [review]

**Comment by anilhelvaci** [comment]
> One of the failing tests is just a check that the API doesn't change. Just add `getRoundId` to the list.
> 
> I'm not sure what the other test failure means.

Yep, I'll update `test-exports.ts`. My assumption is two errors are correlated so will focus on the second error after first one is resolved. Thanks for review 🙏

**Comment by anilhelvaci** [comment]
Hey @turadg - the CI fails because of this [error](https://github.com/Agoric/agoric-3-proposals/actions/runs/11332308733/job/31514152940?pr=183#annotation:11:69). Any chance it's because the PR is from a fork?

**Comment by turadg** [comment]
> Hey @turadg - the CI fails because of this [error](https://github.com/Agoric/agoric-3-proposals/actions/runs/11332308733/job/31514152940?pr=183#annotation:11:69). Any chance it's because the PR is from a fork?

Good hypothesis. I've initiated a re-run that will I hope will run with my privileges

**Comment by anilhelvaci** [comment]
> Good hypothesis. I've initiated a re-run that will I hope will run with my privileges

Hello @turadg , we didn't have any luck with this one. What else do you think we can try?

**Pull request closed without merging**
